Added methods to extract exif data
lukaszkoc98/ImagesIndex pull request #12
Opened 2022-03-20 11:38 UTC by TomaszMaciazek

2022-03-21 19:37 UTC, lukaszkoc98 requested changes

2022-03-21 19:39 UTC, TomaszMaciazek commented on src/PhotoCatalog.WebAPI/PhotoCatalog.WebAPI/PhotoCatalog.API/Controllers/ImageController.cs
> +            var folderName = Path.Combine("Resources", "Images");
To jest endpoint tymczasowy do dogadania z Jankiem jak będzie upload robił

2022-03-21 19:40 UTC, TomaszMaciazek commented on src/PhotoCatalog.WebAPI/PhotoCatalog.WebAPI/PhotoCatalog.Model/DTO/ImageDTO.cs
> +        public ushort? Flash { get; set; }
wartość enuma Flash rzutujemy na ushort żeby nie dodawać zależności DTO od paczki zewnętrznej. Dla frontendu i tak przesłana jest wartość liczbowa

2022-03-21 19:44 UTC, lukaszkoc98 approved these changes

2022-03-22 08:03 UTC, Jan-Gabzdyl commented on src/PhotoCatalog.WebAPI/PhotoCatalog.WebAPI/PhotoCatalog.API/Controllers/ImageController.cs
> +            var folderName = Path.Combine("Resources", "Images");
Myślę, że nawet ten endpoint może tak zostać

2022-03-23 17:51 UTC, merged